2024-11-06 19:48:08,472 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\Module 4\Module 12\tests_12_4.py", line 71, in test_run
    func_runner = Runner(54)
                  ^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\Module 4\Module 12\tests_12_4.py", line 10, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-11-06 19:48:08,473 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\Module 4\Module 12\tests_12_4.py", line 60, in test_walk
    func_runner = Runner('Walk', speed=-5)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\Module 4\Module 12\tests_12_4.py", line 15, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
